[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "prymes"
authors = [{name = "Jingyang Wang", email = "wangjy2010@126.com"}]
dynamic = ["version", "description"]
